
# Get select face id

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Channel/GetClockInfo"
}

####

# Select channel

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Channel/SetIndex",
  "SelectIndex": 3
}

####

# Get current channel

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Channel/GetIndex"
}

####

# set display brightness

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Channel/SetBrightness",
  "Brightness": 100
}

####

# get all setting

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Channel/GetAllConf"
}

####

# Visualizer Channel

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Channel/SetEqPosition",
  "EqPosition": 0
}

####

# Play Buzzer

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Device/PlayBuzzer",
  "ActiveTimeInCycle": 500,
  "OffTimeInCycle": 500,
  "PlayTotalTime": 3000
}

####

# Reset sending animation PicId

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Draw/ResetHttpGifId"
}

####

# Send animation

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command":"Draw/SendHttpGif",
  "PicNum":1,
  "PicWidth":64,
  "PicOffset":0,
  "PicID":1,
  "PicSpeed":100,
  "PicData":""
}

####

# Clear all text area

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command": "Draw/ClearHttpText"
}

####

# display text

POST http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

{
  "Command":"Draw/SendHttpText",
  "TextId":4,
  "x":4,
  "y":26,
  "dir":0,
  "font":3,
  "TextWidth":64,
  "speed":10,
  "TextString":"Divoom",
  "color":"#0000FF",
  "align":1
}


####

# display text

GET http://192.168.2.163/post
Content-Type: application/json
Accept: application/json

